---
baseURL:                "http://localhost:1313/"
languageCode:           "en-gb"
title:                  "James Kingsbury"
disableLiveReload:      true
watch:                  true
preservetaxonomynames:  true

params:
  description:   "Full stack developer based in the UK"
  author:        "James Kingsbury"
  title_first:   "James"
  title_last:    "Kingsbury"
  no_index:      true
  cl_image_base: "/imgs/"

menu:
  main:
    - name:        "home"
      identifier:  "home"
      url:         "/"
      weight:      1
    - name:        "projects"
      identifier:  "projects"
      url:         "/projects"
      weight:      2
    - name:        "cv"
      identifier:  "cv"
      url:         "/cv"
      weight:      3
    - name:        "contact me"
      identifier:  "contact-me"
      url:         "/contact"
      weight:      5

taxonomies:
  language:       "Languages"
  framework:      "Frameworks"
  infrastructure: "Infrastructure"
  tool:           "Tools"
  category:       "Categories"
...
